### ISSUE TITLE
A more comprehensive error message

### ISSUE THREAD

**Issue by albertputrapurnama** [spruceid/siwe-go#14]
# General Description
I have a question regarding siwe-go's error implementation. I am having difficulty debugging when there's some parsing/serialization error when using `siwe.ParseMessage`  this is mainly because the `Error()` implementation hides the specific error message.

# Specific Example
Specifically if I initialize using something like:
```
msg, err := siwe.InitMessage(
		challengeReq.Domain,
		challengeReq.Identifier,
		challengeReq.URI,
		"some-random-version", // incorrect siwe message version
		msgOptions,
	)
```
Then try to parse it using `siwe.ParseMessage`, it will return an error `Invalid Message` without explicitly specifying which part of the message is invalid. In this case, I think I should have a way to get  `Message could not be parsed` message from the error since the regex validation failed.

# Proposed Solution
I want to try to open a discussion here on how to handle this. But there's generally 2 things that I think we need to address:

1. Have some way for devs to get a more specific error message outside of the default `Error()` implementation.
2. A more granular regular expression validation, resulting in a better error handling in addition to (1).

For (1), I think since `siwe` already have Error types such as `ExpiredMessage`, `InvalidMessage`, `InvalidSignature`, we can just make the error string public so that developers can type cast the error into one of these types and see the string message for themselves.
For (2), A way that I think should work is to break apart the `regexp.Regexp` validation into smaller `regexp.Regexp` so that we can find out exactly where the expression fail.

**Comment by awoie** [comment]
@albertputrapurnama can you check whether our latest release fixes your problem?

**Comment by albertputrapurnama** [comment]
@awoie it should be good!

Thank you!
